fail_fast: false
minimum_pre_commit_version: '0'
repos:
  # more info on the usage: https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
  - repo: https://github.com/golangci/golangci-lint
    rev: 114493f9b3e7257d29e4130f2b4a4aadefbb6845 # v2.14.0
    hooks:
      - id: golangci-lint-full
        language_version: 1.26.5
        stages: [pre-commit]
      - id: golangci-lint-fmt
        language_version: 1.26.5
        stages: [pre-commit]
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: 85389ec4903aa23ebe6e650730e6f7c558a38648 # v1.6.1
    hooks:
      - id: clang-format
        args:
          - --version=19
      - id: clang-tidy
        args:
          - --version=19
          - --checks=.clang-tidy
        files: ^bpf/.*\.c$
  - repo: https://github.com/yoheimuta/protolint
    rev: c5433e2d6826441fc6150e7eb0ff5ad568100ad5 # v0.58.0
    hooks:
      - id: protolint
