name: Update RuntimeEnforcement chart versions

sources:
  chartVersion:
    name: "Get latest runtime-enforcement helm version"
    kind: yaml
    transformers:
      - semverinc: patch
    spec:
      file: charts/runtime-enforcement/Chart.yaml
      key: $.version
  releaseVersion:
    name: "Get latest runtime-enforcement version"
    kind: githubrelease
    spec:
      owner: '{{ requiredEnv .github.owner }}'
      repository: runtime-enforcement
      token: '{{ requiredEnv .github.token }}'
      versionfilter:
        kind: "semver"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.author }}"
      email: "{{ .github.email }}"
      directory: "/tmp/helm-charts"
      owner: "{{ requiredEnv .github.owner }}"
      repository: "runtime-enforcement"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ requiredEnv .github.user }}"
      branch: "{{ .github.branch }}"
      commitmessage:
        type: "chore"
        title: "Update RuntimeEnforcement Helm charts"
        hidecredit: true
        footers: "Signed-off-by: RuntimeEnforcement bot <runtime-enforcement-bot@users.noreply.github.com>"

actions:
  default:
    title: 'chore: Helm chart {{ source "chartVersion" }} release'
    kind: github/pullrequest
    scmid: default
    spec:
      automerge: false
      mergemethod: squash
      description: |
        Automatic Helm chart {{ source "chartVersion" }} update.
        This PR has been created by the automation used to automatically update the Helm charts when RuntimeEnforcement is released or helm chart content is updated.
        REMEMBER IF YOU WANT TO MERGE IN A SINGLE COMMIT CHANGES AND VERSION BUMP, YOU MUST SQUASH THE COMMIT BEFORE MERGING THIS PR!
      draft: false
      labels:
        - "chore"

targets:
  update_helm_version:
    scmid: default
    name: Update Helm chart version
    kind: yaml
    sourceid: chartVersion
    spec:
      file: charts/runtime-enforcement/Chart.yaml
      key: $.version
  update_appversion:
    scmid: default
    name: Update Helm chart appVersion
    kind: yaml
    sourceid: releaseVersion
    spec:
      file: charts/runtime-enforcement/Chart.yaml
      key: $.appVersion
  update_operator_version:
    scmid: default
    name: Update Helm chart operator version
    kind: yaml
    sourceid: releaseVersion
    spec:
      file: charts/runtime-enforcement/values.yaml
      key: $.operator.manager.image.tag
  update_daemon_version:
    scmid: default
    name: Update Helm chart daemon version
    kind: yaml
    sourceid: releaseVersion
    spec:
      file: charts/runtime-enforcement/values.yaml
      key: $.daemon.daemon.image.tag
