name: "Bug report"
labels: ["bug", "triage"]
description: Create a report to help runtime-enforcement to improve
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu
          - **Architecture**: arm64
          - **Cluster**: RKE2
      value: |
        - OS:
        - Architecture:
        - Cluster:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Issue Description
      description: A concise description of what you're experiencing
      value: |
        - Expected behavior:
        - Current behavior:
        - Steps to reproduce:
    validations:
      required: false
