name: "Feature Request"
labels: ["triage"]
description: Create a feature request to help us improve
title: "Feature Request: "
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solution you'd like
      description: A clear and concise description of what you want to happen
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false
