name: Runtime Enforcer Release
title: "Runtime Enforcer <VERSION> release"
description: Issue with all the items needed to release a new version of Runtime Enforcer Release
projects: ["rancher-sandbox/8"]

body:
  - type: markdown
    attributes:
      value: |
        This issue tracks the release of a new version of Runtime Enforcer. 

  - type: textarea
    attributes:
      label: Checklist
      description: Base checklist for the release process. Please, add or remove items as needed.
      value: |
        This issue tracks the release of a new version of Runtime Enforcer. Please follow the checklist below to ensure a smooth release process.
        - [ ] Make sure CI is green
        - [ ] Create a *draft* release with the version tag and generate release notes.
        - [ ] Tag runtime-enforcer
        - [ ] Verify the "Create a new release for RuntimeEnforcer (release.yml)" workflow completes without problem
          - [ ] Verify the draft release is now published
          - [ ] Verify that the container images are published on ghcr.io
        - [ ] Check if updatecli opens a PR updating the Helm charts with the correct changes.
          - [ ] Check if agent and operator's image versions are correctly bumped. 
          - [ ] Check if app version and chart version are correctly bumped.
          - [ ] Check if CI for the Helm chart PR is green. If so, merge it.
        - [ ] Verify that helm release is correctly created and new version in helm repo is accessible.
