// Package v1alpha1 contains API Schema definitions for the security v1alpha1 API group.
// +kubebuilder:object:generate=true
// +groupName=security.rancher.io
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// GroupName is the group name used in this package.
const GroupName = "security.rancher.io"

// SchemeGroupVersion is group version used to register these objects.
//
//nolint:gochecknoglobals // Required to be global by pkg/generated/*
var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1alpha1"}

var (
	// GroupVersion is group version used to register these objects.
	//nolint:gochecknoglobals // Generated by kubebuilder
	GroupVersion = schema.GroupVersion{Group: "security.rancher.io", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
	//nolint:gochecknoglobals // Generated by kubebuilder
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	//nolint:gochecknoglobals // Generated by kubebuilder
	AddToScheme = SchemeBuilder.AddToScheme
)

// Resource takes an unqualified resource and returns back a Group qualified GroupResource.
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}
