package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	// DeployCondition is a condition set when WorkloadPolicy controller has
	// deployed the policy to the system.
	DeployCondition = "Deployed"

	// SyncFailedReason is set when the reconcile fails.
	SyncFailedReason = "SyncFailed"

	DeployedState = "Deployed"
	ErrorState    = "Error"

	// WorkloadPolicyFinalizer is added to WorkloadPolicy resources to ensure
	// they are not deleted while still in use by Pods.
	WorkloadPolicyFinalizer = "workloadpolicy.security.rancher.io/finalizer"
)

type WorkloadPolicyExecutables struct {
	// allowed defines a list of executables that are allowed to run
	// +optional
	Allowed []string `json:"allowed,omitempty"`
}

type WorkloadPolicyRules struct {
	// executables defines a security policy for executables.
	// +optional
	Executables WorkloadPolicyExecutables `json:"executables,omitempty"`
}

type WorkloadPolicySpec struct {
	// mode defines the execution mode of this policy. Can be set to
	// either "protect" or "monitor". In "protect" mode, the policy
	// blocks and reports violations, while in "monitor" mode,
	// it only reports violations.
	// +kubebuilder:validation:Enum=monitor;protect
	// +kubebuilder:validation:Required
	Mode string `json:"mode,omitempty"`

	// rulesByContainer specifies for each container the list of rules to apply.
	RulesByContainer map[string]*WorkloadPolicyRules `json:"rulesByContainer,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Mode",type=string,JSONPath=`.spec.mode`
// +kubebuilder:printcolumn:name="Status",type=string,JSONPath=`.status.state`
// +kubebuilder:printcolumn:name="Reason",type=string,priority=1,JSONPath=`.status.reason`
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// WorkloadPolicy is the Schema for the workloadpolicies API.
type WorkloadPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec WorkloadPolicySpec `json:"spec,omitempty"`
}

// +kubebuilder:object:root=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// WorkloadPolicyList contains a list of WorkloadPolicy.
type WorkloadPolicyList struct {
	metav1.TypeMeta `json:",inline"`

	metav1.ListMeta `json:"metadata,omitempty"`

	Items []WorkloadPolicy `json:"items"`
}

//nolint:gochecknoinits // Generated by kubebuilder
func init() {
	SchemeBuilder.Register(&WorkloadPolicy{}, &WorkloadPolicyList{})
}
