//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposal) DeepCopyInto(out *WorkloadPolicyProposal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposal.
func (in *WorkloadPolicyProposal) DeepCopy() *WorkloadPolicyProposal {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPolicyProposal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalCondition) DeepCopyInto(out *WorkloadPolicyProposalCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalCondition.
func (in *WorkloadPolicyProposalCondition) DeepCopy() *WorkloadPolicyProposalCondition {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalList) DeepCopyInto(out *WorkloadPolicyProposalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadPolicyProposal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalList.
func (in *WorkloadPolicyProposalList) DeepCopy() *WorkloadPolicyProposalList {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPolicyProposalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalSpec) DeepCopyInto(out *WorkloadPolicyProposalSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RulesByContainer != nil {
		in, out := &in.RulesByContainer, &out.RulesByContainer
		*out = make(map[string]*WorkloadSecurityPolicyRules, len(*in))
		for key, val := range *in {
			var outVal *WorkloadSecurityPolicyRules
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(WorkloadSecurityPolicyRules)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalSpec.
func (in *WorkloadPolicyProposalSpec) DeepCopy() *WorkloadPolicyProposalSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalStatus) DeepCopyInto(out *WorkloadPolicyProposalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WorkloadPolicyProposalCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalStatus.
func (in *WorkloadPolicyProposalStatus) DeepCopy() *WorkloadPolicyProposalStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSecurityPolicy) DeepCopyInto(out *WorkloadSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSecurityPolicy.
func (in *WorkloadSecurityPolicy) DeepCopy() *WorkloadSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSecurityPolicyExecutables) DeepCopyInto(out *WorkloadSecurityPolicyExecutables) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedPrefixes != nil {
		in, out := &in.AllowedPrefixes, &out.AllowedPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSecurityPolicyExecutables.
func (in *WorkloadSecurityPolicyExecutables) DeepCopy() *WorkloadSecurityPolicyExecutables {
	if in == nil {
		return nil
	}
	out := new(WorkloadSecurityPolicyExecutables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSecurityPolicyList) DeepCopyInto(out *WorkloadSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadSecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSecurityPolicyList.
func (in *WorkloadSecurityPolicyList) DeepCopy() *WorkloadSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(WorkloadSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSecurityPolicyRules) DeepCopyInto(out *WorkloadSecurityPolicyRules) {
	*out = *in
	in.Executables.DeepCopyInto(&out.Executables)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSecurityPolicyRules.
func (in *WorkloadSecurityPolicyRules) DeepCopy() *WorkloadSecurityPolicyRules {
	if in == nil {
		return nil
	}
	out := new(WorkloadSecurityPolicyRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSecurityPolicySpec) DeepCopyInto(out *WorkloadSecurityPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RulesByContainer != nil {
		in, out := &in.RulesByContainer, &out.RulesByContainer
		*out = make(map[string]*WorkloadSecurityPolicyRules, len(*in))
		for key, val := range *in {
			var outVal *WorkloadSecurityPolicyRules
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(WorkloadSecurityPolicyRules)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSecurityPolicySpec.
func (in *WorkloadSecurityPolicySpec) DeepCopy() *WorkloadSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSecurityPolicyStatus) DeepCopyInto(out *WorkloadSecurityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSecurityPolicyStatus.
func (in *WorkloadSecurityPolicyStatus) DeepCopy() *WorkloadSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
