// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentObserver_ListPoliciesStatus_FullMethodName = "/runtimeenforcer.agent.v1.AgentObserver/ListPoliciesStatus"
	AgentObserver_ListPodCache_FullMethodName       = "/runtimeenforcer.agent.v1.AgentObserver/ListPodCache"
)

// AgentObserverClient is the client API for AgentObserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentObserver exposes agent internal state for external components.
type AgentObserverClient interface {
	// ListPoliciesStatus returns the status of workload Policies.
	ListPoliciesStatus(ctx context.Context, in *ListPoliciesStatusRequest, opts ...grpc.CallOption) (*ListPoliciesStatusResponse, error)
	// ListPodCache returns the current pod cache.
	ListPodCache(ctx context.Context, in *ListPodCacheRequest, opts ...grpc.CallOption) (*ListPodCacheResponse, error)
}

type agentObserverClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentObserverClient(cc grpc.ClientConnInterface) AgentObserverClient {
	return &agentObserverClient{cc}
}

func (c *agentObserverClient) ListPoliciesStatus(ctx context.Context, in *ListPoliciesStatusRequest, opts ...grpc.CallOption) (*ListPoliciesStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesStatusResponse)
	err := c.cc.Invoke(ctx, AgentObserver_ListPoliciesStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentObserverClient) ListPodCache(ctx context.Context, in *ListPodCacheRequest, opts ...grpc.CallOption) (*ListPodCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPodCacheResponse)
	err := c.cc.Invoke(ctx, AgentObserver_ListPodCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentObserverServer is the server API for AgentObserver service.
// All implementations must embed UnimplementedAgentObserverServer
// for forward compatibility.
//
// AgentObserver exposes agent internal state for external components.
type AgentObserverServer interface {
	// ListPoliciesStatus returns the status of workload Policies.
	ListPoliciesStatus(context.Context, *ListPoliciesStatusRequest) (*ListPoliciesStatusResponse, error)
	// ListPodCache returns the current pod cache.
	ListPodCache(context.Context, *ListPodCacheRequest) (*ListPodCacheResponse, error)
	mustEmbedUnimplementedAgentObserverServer()
}

// UnimplementedAgentObserverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentObserverServer struct{}

func (UnimplementedAgentObserverServer) ListPoliciesStatus(context.Context, *ListPoliciesStatusRequest) (*ListPoliciesStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPoliciesStatus not implemented")
}
func (UnimplementedAgentObserverServer) ListPodCache(context.Context, *ListPodCacheRequest) (*ListPodCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPodCache not implemented")
}
func (UnimplementedAgentObserverServer) mustEmbedUnimplementedAgentObserverServer() {}
func (UnimplementedAgentObserverServer) testEmbeddedByValue()                       {}

// UnsafeAgentObserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentObserverServer will
// result in compilation errors.
type UnsafeAgentObserverServer interface {
	mustEmbedUnimplementedAgentObserverServer()
}

func RegisterAgentObserverServer(s grpc.ServiceRegistrar, srv AgentObserverServer) {
	// If the following call panics, it indicates UnimplementedAgentObserverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentObserver_ServiceDesc, srv)
}

func _AgentObserver_ListPoliciesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentObserverServer).ListPoliciesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentObserver_ListPoliciesStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentObserverServer).ListPoliciesStatus(ctx, req.(*ListPoliciesStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentObserver_ListPodCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentObserverServer).ListPodCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentObserver_ListPodCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentObserverServer).ListPodCache(ctx, req.(*ListPodCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentObserver_ServiceDesc is the grpc.ServiceDesc for AgentObserver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentObserver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtimeenforcer.agent.v1.AgentObserver",
	HandlerType: (*AgentObserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPoliciesStatus",
			Handler:    _AgentObserver_ListPoliciesStatus_Handler,
		},
		{
			MethodName: "ListPodCache",
			Handler:    _AgentObserver_ListPodCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/v1/agent.proto",
}
