// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyState int32

const (
	PolicyState_POLICY_STATE_UNSPECIFIED PolicyState = 0
	// Policy present, loaded and actively running.
	PolicyState_POLICY_STATE_READY PolicyState = 1
	// Agent attempted to load/apply policy and it failed.
	PolicyState_POLICY_STATE_ERROR PolicyState = 2
)

// Enum value maps for PolicyState.
var (
	PolicyState_name = map[int32]string{
		0: "POLICY_STATE_UNSPECIFIED",
		1: "POLICY_STATE_READY",
		2: "POLICY_STATE_ERROR",
	}
	PolicyState_value = map[string]int32{
		"POLICY_STATE_UNSPECIFIED": 0,
		"POLICY_STATE_READY":       1,
		"POLICY_STATE_ERROR":       2,
	}
)

func (x PolicyState) Enum() *PolicyState {
	p := new(PolicyState)
	*p = x
	return p
}

func (x PolicyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (PolicyState) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[0]
}

func (x PolicyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyState.Descriptor instead.
func (PolicyState) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type PolicyMode int32

const (
	PolicyMode_POLICY_MODE_UNSPECIFIED PolicyMode = 0
	// Policy monitor mode
	PolicyMode_POLICY_MODE_MONITOR PolicyMode = 1
	// Policy protect mode
	PolicyMode_POLICY_MODE_PROTECT PolicyMode = 2
)

// Enum value maps for PolicyMode.
var (
	PolicyMode_name = map[int32]string{
		0: "POLICY_MODE_UNSPECIFIED",
		1: "POLICY_MODE_MONITOR",
		2: "POLICY_MODE_PROTECT",
	}
	PolicyMode_value = map[string]int32{
		"POLICY_MODE_UNSPECIFIED": 0,
		"POLICY_MODE_MONITOR":     1,
		"POLICY_MODE_PROTECT":     2,
	}
)

func (x PolicyMode) Enum() *PolicyMode {
	p := new(PolicyMode)
	*p = x
	return p
}

func (x PolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (PolicyMode) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[1]
}

func (x PolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyMode.Descriptor instead.
func (PolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type ListPoliciesStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusRequest) Reset() {
	*x = ListPoliciesStatusRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusRequest) ProtoMessage() {}

func (x *ListPoliciesStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type PolicyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         PolicyState            `protobuf:"varint,1,opt,name=state,proto3,enum=runtimeenforcer.agent.v1.PolicyState" json:"state,omitempty"`
	Mode          PolicyMode             `protobuf:"varint,2,opt,name=mode,proto3,enum=runtimeenforcer.agent.v1.PolicyMode" json:"mode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStatus) Reset() {
	*x = PolicyStatus{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatus) ProtoMessage() {}

func (x *PolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatus.ProtoReflect.Descriptor instead.
func (*PolicyStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyStatus) GetState() PolicyState {
	if x != nil {
		return x.State
	}
	return PolicyState_POLICY_STATE_UNSPECIFIED
}

func (x *PolicyStatus) GetMode() PolicyMode {
	if x != nil {
		return x.Mode
	}
	return PolicyMode_POLICY_MODE_UNSPECIFIED
}

func (x *PolicyStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPoliciesStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Policies      map[string]*PolicyStatus `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesStatusResponse) Reset() {
	*x = ListPoliciesStatusResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesStatusResponse) ProtoMessage() {}

func (x *ListPoliciesStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesStatusResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ListPoliciesStatusResponse) GetPolicies() map[string]*PolicyStatus {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\x18runtimeenforcer.agent.v1\"\x1b\n" +
	"\x19ListPoliciesStatusRequest\"\x9f\x01\n" +
	"\fPolicyStatus\x12;\n" +
	"\x05state\x18\x01 \x01(\x0e2%.runtimeenforcer.agent.v1.PolicyStateR\x05state\x128\n" +
	"\x04mode\x18\x02 \x01(\x0e2$.runtimeenforcer.agent.v1.PolicyModeR\x04mode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe1\x01\n" +
	"\x1aListPoliciesStatusResponse\x12^\n" +
	"\bpolicies\x18\x01 \x03(\v2B.runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntryR\bpolicies\x1ac\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.runtimeenforcer.agent.v1.PolicyStatusR\x05value:\x028\x01*[\n" +
	"\vPolicyState\x12\x1c\n" +
	"\x18POLICY_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12POLICY_STATE_READY\x10\x01\x12\x16\n" +
	"\x12POLICY_STATE_ERROR\x10\x02*[\n" +
	"\n" +
	"PolicyMode\x12\x1b\n" +
	"\x17POLICY_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POLICY_MODE_MONITOR\x10\x01\x12\x17\n" +
	"\x13POLICY_MODE_PROTECT\x10\x022\x93\x01\n" +
	"\rAgentObserver\x12\x81\x01\n" +
	"\x12ListPoliciesStatus\x123.runtimeenforcer.agent.v1.ListPoliciesStatusRequest\x1a4.runtimeenforcer.agent.v1.ListPoliciesStatusResponse\"\x00B>Z<github.com/neuvector/runtime-enforcer/proto/agent/v1;agentv1b\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(PolicyState)(0),                   // 0: runtimeenforcer.agent.v1.PolicyState
	(PolicyMode)(0),                    // 1: runtimeenforcer.agent.v1.PolicyMode
	(*ListPoliciesStatusRequest)(nil),  // 2: runtimeenforcer.agent.v1.ListPoliciesStatusRequest
	(*PolicyStatus)(nil),               // 3: runtimeenforcer.agent.v1.PolicyStatus
	(*ListPoliciesStatusResponse)(nil), // 4: runtimeenforcer.agent.v1.ListPoliciesStatusResponse
	nil,                                // 5: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	0, // 0: runtimeenforcer.agent.v1.PolicyStatus.state:type_name -> runtimeenforcer.agent.v1.PolicyState
	1, // 1: runtimeenforcer.agent.v1.PolicyStatus.mode:type_name -> runtimeenforcer.agent.v1.PolicyMode
	5, // 2: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.policies:type_name -> runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry
	3, // 3: runtimeenforcer.agent.v1.ListPoliciesStatusResponse.PoliciesEntry.value:type_name -> runtimeenforcer.agent.v1.PolicyStatus
	2, // 4: runtimeenforcer.agent.v1.AgentObserver.ListPoliciesStatus:input_type -> runtimeenforcer.agent.v1.ListPoliciesStatusRequest
	4, // 5: runtimeenforcer.agent.v1.AgentObserver.ListPoliciesStatus:output_type -> runtimeenforcer.agent.v1.ListPoliciesStatusResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
