= Troubleshooting

This document provides guidance for diagnosing issues with runtime-enforcer.

== Enable verbose logs

To enable more verbose logs in each container via Helm values:
[source,bash]
----
helm upgrade --install runtime-enforcer runtime-enforcer/runtime-enforcer \
  --namespace runtime-enforcer \
  --set agent.logLevel=debug \
  --set controller.logLevel=debug \
  --reuse-values
----

== Debugger

The debugger is an optional Kubernetes Deployment that helps diagnose issues between the runtime-enforcer agents and the actual state of the Kubernetes cluster.

At the moment, it supports only a few basic operations listed below.

=== Features

==== Cache comparison

Each agent maintains an in-memory cache of the pods and containers it is aware of on its node.
This cache is populated via the https://github.com/containerd/nri[NRI (Node Resource Interface)] plugin and is used to resolve container identities during policy enforcement.

If the agent cache drifts from the real cluster state, enforcement decisions could be applied incorrectly so it's important to validate if the cache is in sync.

The debugger periodically:

1. Queries every agent (via mTLS-secured gRPC) for its current pod/container cache.
2. Lists all pods from the Kubernetes API.
3. Compares the two views node-by-node and prints a diff to stdout.

If the caches are aligned you will see:

----
caches are aligned
----

If there is a discrepancy you will see a diff with the affected node and pods, followed by a full dump of the agent cache for that node.

== NRI timeouts and required plugins

Runtime Enforcer relies on NRI (Node Resource Interface) integration provided by the container runtime.

Some environments may hit the NRI default request timeout (`5s` to register a plugin and `2s` to handle an event), which can cause the NRI plugin to be detached from the container runtime. This can cause the agent to repeatedly retry connecting to the NRI plugin, resulting in the agent not coming up as expected.

When this happens, you would see runtime-enforcer agent crashing with the following information in its logs:

----
{"time":"2026-04-24T15:36:07.617127725Z","level":"INFO","msg":"ttrpc server closed 00-runtime-enforcer-agent : ttrpc: server closed","component":"agent","component":"nri-handler","component":"nri-stub"}
----

You will also see logs like the following in containerd's logs, indicating that the configured timeout value was exceeded:

----
Apr 24 15:36:27 kind-control-plane containerd[114]: time="2026-04-24T15:36:27.664534740Z" level=info msg="connection to plugin \"00-runtime-enforcer-agent\" closed"
Apr 24 15:36:27 kind-control-plane containerd[114]: time="2026-04-24T15:36:27.664575617Z" level=info msg="failed to synchronize plugin: context deadline exceeded"
Apr 24 15:39:38 kind-control-plane containerd[114]: time="2026-04-24T15:39:38.782163498Z" level=error msg="closing plugin 00-runtime-enforcer-agent, failed to handle event 6: context deadline exceeded"
----

To mitigate this, you can increase the NRI timeout on the container runtime side by editing the container runtime configuration file.

=== containerd: increase NRI timeout

Edit `/etc/containerd/config.toml` and update the NRI plugin timeouts under `[plugins."io.containerd.nri.v1.nri"]`:

The example below changes the settings to `10s` and `5s`.

[source,toml]
----
[plugins."io.containerd.nri.v1.nri"]
  # plugin_registration_timeout is the timeout for a plugin to register after connection.
  plugin_registration_timeout = "10s"
  # plugin_request_timeout is the timeout for a plugin to handle an event/request.
  plugin_request_timeout = "5s"
----

For details and additional NRI settings, see https://github.com/containerd/containerd/blob/main/docs/NRI.md#disabling-nri-support-in-containerd[containerd NRI configuration documentation].

=== CRI-O: increase NRI timeout

Edit `/etc/crio/crio.conf` and update the `crio.nri` table:

The example below changes the setting to `10s` and `5s`.

[source,toml]
----
[crio.nri]
  # Timeout for a plugin to register itself with NRI.
  nri_plugin_registration_timeout = "10s"
  # Timeout for a plugin to handle an NRI request.
  nri_plugin_request_timeout = "5s"
----

For details, see https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md#crionri-table[CRI-O NRI configuration documentation].

=== Required Plugins

Additionally, recent container runtimes provide an option to require a set of NRI plugins to always be present for container creation to succeed.

Follow the steps below to configure this on a per-workload basis. Check https://github.com/containerd/nri/blob/57442b2a20c63d48d69dc600c3fb4f0c063c7ef0/docs/validation-plugins.md#dealing-with-required-plugins[NRI docs] for more information about the best option to suit your environment.

==== Prerequisites

The *required plugins* feature is available since *containerd 2.2* and *CRI-O 1.34.0*.

==== Workloads

For workloads that you want to ensure have runtime-enforcer protection present, add the `required-plugins.noderesource.dev` annotation to its pod spec:

[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
        security.rancher.io/policy: workloadpolicy-sample
      annotations:
        # This specifies "runtime-enforcer-agent" plugin to be required.
        required-plugins.noderesource.dev: '["runtime-enforcer-agent"]'
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        stdin: true
        tty: true
----

When the required plugin is not available for any reason, the workload will fail to start with errors in Kubernetes events:

----
4s          Warning   Failed                    pod/ubuntu-deployment-6655f5c7ff-xghnd    Error: failed to create containerd container: failed to get NRI adjustment for container: validator "00-default-validator" rejected container adjustment, reason: validation error: required plugin "runtime-enforcer-agent" not present
----

==== containerd: required_plugins

In `/etc/containerd/config.toml`, enable the `default_validator`:

[source,toml]
----
[plugins."io.containerd.nri.v1.nri".default_validator]
  enable = true
----

==== CRI-O: nri_validator_required_plugins

In `/etc/crio/crio.conf`, configure the `crio.nri.default_validator` table to enable the default validator:

[source,toml]
----
[crio.nri.default_validator]
  nri_enable_default_validator = true
----

=== Enabling the debugger

The debugger is disabled by default. Enable it via Helm values:

[source,bash]
----
helm upgrade --install runtime-enforcer runtime-enforcer/runtime-enforcer \
  --namespace runtime-enforcer \
  --set debugger.enabled=true \
  --reuse-values
----

NOTE: `--reuse-values` is important because allows you to enable/disable the debugger without restarting the agent.

If you want to customize how often the debugger compares the agent cache against the cluster state, you can set the `debugger.interval` value in your Helm command:

[source,bash]
----
  --set debugger.interval=<interval> # e.g. 1m, 30s
----

=== Viewing debugger output

Once the debugger pod is running, inspect its logs:

[source,bash]
----
kubectl logs -n runtime-enforcer -l app.kubernetes.io/component=debugger -f
----
