// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfLoadConf struct {
	_               structs.HostLayout
	CgrpFsMagic     uint64
	Cgrpv1SubsysIdx uint32
	DebugMode       uint8
	Pad             [3]uint8
}

type bpfProcessEvt struct {
	_           structs.HostLayout
	Cgid        uint64
	CgTrackerId uint64
	PathLen     uint16
	Mode        uint8
	Path        [16384]int8
	_           [5]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	EnforceCgroupPolicy      *ebpf.ProgramSpec `ebpf:"enforce_cgroup_policy"`
	ExecveSend               *ebpf.ProgramSpec `ebpf:"execve_send"`
	TgCgtrackerCgroupMkdir   *ebpf.ProgramSpec `ebpf:"tg_cgtracker_cgroup_mkdir"`
	TgCgtrackerCgroupRelease *ebpf.ProgramSpec `ebpf:"tg_cgtracker_cgroup_release"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CgToPolicyMap        *ebpf.MapSpec `ebpf:"cg_to_policy_map"`
	CgtrackerMap         *ebpf.MapSpec `ebpf:"cgtracker_map"`
	PolStrMaps0          *ebpf.MapSpec `ebpf:"pol_str_maps_0"`
	PolStrMaps1          *ebpf.MapSpec `ebpf:"pol_str_maps_1"`
	PolStrMaps10         *ebpf.MapSpec `ebpf:"pol_str_maps_10"`
	PolStrMaps2          *ebpf.MapSpec `ebpf:"pol_str_maps_2"`
	PolStrMaps3          *ebpf.MapSpec `ebpf:"pol_str_maps_3"`
	PolStrMaps4          *ebpf.MapSpec `ebpf:"pol_str_maps_4"`
	PolStrMaps5          *ebpf.MapSpec `ebpf:"pol_str_maps_5"`
	PolStrMaps6          *ebpf.MapSpec `ebpf:"pol_str_maps_6"`
	PolStrMaps7          *ebpf.MapSpec `ebpf:"pol_str_maps_7"`
	PolStrMaps8          *ebpf.MapSpec `ebpf:"pol_str_maps_8"`
	PolStrMaps9          *ebpf.MapSpec `ebpf:"pol_str_maps_9"`
	PolicyModeMap        *ebpf.MapSpec `ebpf:"policy_mode_map"`
	ProcessEvtStorageMap *ebpf.MapSpec `ebpf:"process_evt_storage_map"`
	RingbufExecve        *ebpf.MapSpec `ebpf:"ringbuf_execve"`
	RingbufMonitoring    *ebpf.MapSpec `ebpf:"ringbuf_monitoring"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	LoadTimeConfig *ebpf.VariableSpec `ebpf:"load_time_config"`
	Unused         *ebpf.VariableSpec `ebpf:"unused"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CgToPolicyMap        *ebpf.Map `ebpf:"cg_to_policy_map"`
	CgtrackerMap         *ebpf.Map `ebpf:"cgtracker_map"`
	PolStrMaps0          *ebpf.Map `ebpf:"pol_str_maps_0"`
	PolStrMaps1          *ebpf.Map `ebpf:"pol_str_maps_1"`
	PolStrMaps10         *ebpf.Map `ebpf:"pol_str_maps_10"`
	PolStrMaps2          *ebpf.Map `ebpf:"pol_str_maps_2"`
	PolStrMaps3          *ebpf.Map `ebpf:"pol_str_maps_3"`
	PolStrMaps4          *ebpf.Map `ebpf:"pol_str_maps_4"`
	PolStrMaps5          *ebpf.Map `ebpf:"pol_str_maps_5"`
	PolStrMaps6          *ebpf.Map `ebpf:"pol_str_maps_6"`
	PolStrMaps7          *ebpf.Map `ebpf:"pol_str_maps_7"`
	PolStrMaps8          *ebpf.Map `ebpf:"pol_str_maps_8"`
	PolStrMaps9          *ebpf.Map `ebpf:"pol_str_maps_9"`
	PolicyModeMap        *ebpf.Map `ebpf:"policy_mode_map"`
	ProcessEvtStorageMap *ebpf.Map `ebpf:"process_evt_storage_map"`
	RingbufExecve        *ebpf.Map `ebpf:"ringbuf_execve"`
	RingbufMonitoring    *ebpf.Map `ebpf:"ringbuf_monitoring"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CgToPolicyMap,
		m.CgtrackerMap,
		m.PolStrMaps0,
		m.PolStrMaps1,
		m.PolStrMaps10,
		m.PolStrMaps2,
		m.PolStrMaps3,
		m.PolStrMaps4,
		m.PolStrMaps5,
		m.PolStrMaps6,
		m.PolStrMaps7,
		m.PolStrMaps8,
		m.PolStrMaps9,
		m.PolicyModeMap,
		m.ProcessEvtStorageMap,
		m.RingbufExecve,
		m.RingbufMonitoring,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	LoadTimeConfig *ebpf.Variable `ebpf:"load_time_config"`
	Unused         *ebpf.Variable `ebpf:"unused"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	EnforceCgroupPolicy      *ebpf.Program `ebpf:"enforce_cgroup_policy"`
	ExecveSend               *ebpf.Program `ebpf:"execve_send"`
	TgCgtrackerCgroupMkdir   *ebpf.Program `ebpf:"tg_cgtracker_cgroup_mkdir"`
	TgCgtrackerCgroupRelease *ebpf.Program `ebpf:"tg_cgtracker_cgroup_release"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.EnforceCgroupPolicy,
		p.ExecveSend,
		p.TgCgtrackerCgroupMkdir,
		p.TgCgtrackerCgroupRelease,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
