FROM docker.io/library/golang:1.25.5 AS builder

RUN apt update
RUN apt install -y build-essential libelf-dev clang llvm libbpf-dev

WORKDIR /src
COPY api/ /src/api
COPY cmd/ /src/cmd
COPY pkg/ /src/pkg
COPY bpf/ /src/bpf/
COPY internal/ /src/internal
COPY go.mod go.sum /src/
COPY Makefile /src/
RUN make daemon

FROM scratch
WORKDIR /
COPY --from=builder /src/bin/daemon /daemon

ENTRYPOINT ["/daemon"]
