FROM registry.suse.com/bci/golang:1.25.1 AS builder
WORKDIR /src
COPY api/ /src/api
COPY cmd/ /src/cmd
COPY pkg/ /src/pkg
COPY internal/ /src/internal
COPY go.mod go.sum /src/
COPY Makefile /src/
RUN make operator

FROM scratch
WORKDIR /
COPY --from=builder /src/bin/operator /operator

USER 65532:65532
ENTRYPOINT ["/operator"]
